sudo: required
dist: trusty
language: python
python:
  - "2.7"

env:
  matrix:
    - "TESTDIR=Go/go-std-postgresql"

before_install:
  - pip install colorama==0.3.1
  # Version 2.3 has a nice Counter() and other features
  # but it requires —-allow-external and -—allow-unverified
  - pip install progressbar==2.2
  - pip install requests
  - echo "127.0.0.1 " `hostname` | sudo tee /etc/hosts
  - echo "127.0.0.1 localhost" | sudo tee /etc/hosts

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.3"
  apt:
    packages:
      - mysql-server

before_script:
  - sudo ./config/travis_mysql_setup.sh
  - mysql -uroot < config/create.sql

script:
  # Pick one test in this directory and verify
  - time ./toolset/run-ci.py verify "$TESTDIR"
